
<?php if(!$submit){ ?>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Add product</h1>
    <form action="/product/add?submit=true" method="post">
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" placeholder="Enter title" name="title">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Description</label>
            <textarea class="form-control" id="description" placeholder="Description..." name="description"></textarea>
        </div>
        <div class="form-group">
            <label for="tags">Tags</label>
            <input type="text" class="form-control" id="tags" placeholder="Enter tags" name="tags">
        </div>
        <div class="form-group">
            <label for="price">Price</label>
            <input type="text" class="form-control" id="price" placeholder="Enter price" name="price">
        </div>
        <div class="form-group">
            <label for="stock">Stock</label>
            <input type="text" class="form-control" id="stock" placeholder="Enter stock" name="stock">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>

<div class="container">
<?php }
else if($success){ ?>
    <div class="alert alert-success" role="alert">
    <?php echo $message; ?> 
    </div>
    <a href="/product/add" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Add more</a>

<?php
} else {
?>
    <div class="alert alert-danger" role="alert">
    <?php echo $message; ?> 
    </div>
    <a  class="btn btn-primary btn-lg">Try again</a>

<?php 
} 
?>
</div>
