
<div class="jumbotron jumbotron-fluid">
    <div class="container">
    <h2>List products</h2>
<?php
if ($products->count() > 0 || $products != null ) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#Id</th>
            <th>Titile</th>
            <th>Name</th>
            <th>Tags</th>
            <th>Price</th>
            <th>Syock</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="6">Product count: <?php echo $products->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($products as $product) { ?>
            <tr>
                <td><?php echo $product->id; ?></td>
                <td><?php echo $product->title; ?></td>
                <td><?php echo $product->description; ?></td>
                <td><?php echo $product->tags; ?></td>
                <td><?php echo $product->price; ?></td>
                <td><?php echo $product->stock; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}
?>
</div>
</div>