
<div class="jumbotron jumbotron-fluid">
    <div class="container">
    <h2>List orders</h2>
<?php
if ($orders->count() > 0 || $orders != null ) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#Id</th>
            <th>Customer name</th>
            <th>Customer address</th>
            <th>Zipcode</th>
            <th>Product</th>
            <th>Quantity</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="6">Order count: <?php echo $orders->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($orders as $order) { ?>
            <tr>
                <td><?php echo $order->id; ?></td>
                <td><?php echo $order->customer_name; ?></td>
                <td><?php echo $order->customer_address; ?></td>
                <td><?php echo $order->zipcode; ?></td>
                <td><?php echo $order->product; ?></td>
                <td><?php echo $order->quantity; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}
?>
</div>
</div>