<?php if(!$submit){ ?>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Asign role resource</h1>
    <form action="/acl/manage?submit=true" method="post">
        <div class="form-group">
            <label for="controller">Roles</label>
            <select class="form-control" id="roles" name="role">
                <option selected disabled value="roles">Select any role</option>
                <?php foreach($roles as $role){ ?>
                    <option value="<?php echo $role->role; ?>"><?php echo $role->role; ?></option>
                <?php } ?>
            </select>
        </div>
        <div class="form-group">
            <?php foreach($resources as $resource){ 
                $resource_name = $resource->resource;
                ?>

                <div class="form-check">
                    <input class="form-check-input" type="checkbox" id="<?php echo resource;?>" value="<?php echo $resource->resource;?>" name="<?php echo $resource->resource;?>">
                    <label class="form-check-label" for="<?php echo $resource->resource;?>">
                        <?php echo $resource_name; ?>
                    </label>
                </div>
            <?php } ?>
            
            <!-- <label for="controller">Components</label>
            <select class="form-control" id="roles" name="resource">
                <option selected disabled value="roles">Select any resource</option>
                <?php 
                foreach($controllers as $controller){ ?>
                    <option value="<?php echo $controller; ?>"><?php echo $controller; ?></option>
                <?php } ?>
            </select> -->
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>

<div class="container">
<?php }
else if($success){ ?>
    <div class="alert alert-success" role="alert">
    <?php echo $message; ?> 
    </div>
    <a href="/acl/resource" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Go back</a>

<?php
} else {
?>
    <div class="alert alert-danger" role="alert">
    <?php echo $message; ?> 
    </div>
    <a href="/acl/resource" class="btn btn-primary btn-lg">Go back</a>
<?php 
} 
?>
</div>
<div class="jumbotron jumbotron-fluid">
    <div class="container">
    <h2>List resources</h2>
<?php
if ($aclmanage != null && $aclmanage->count() > 0 ) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#Id</th>
            <th>Role</th>
            <th>Resources</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="2">Total count: <?php echo $aclmanage->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($aclmanage as $resource) { ?>
            <tr>
                <td><?php echo $resource->id; ?></td>
                <td><?php echo $resource->role; ?></td>
                <td><?php echo $resource->resources; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}
else
{
?>
<p>No users found.</p> 
<?php } ?>
</div>
</div>

