<?php if(!$submit){ ?>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Add resource</h1>
    <form action="/acl/resource?submit=true" method="post">
        <div class="form-group">
            <label for="controller">Controller name</label>
            <input type="text" class="form-control" id="controller" placeholder="single controller name like test, index etc." name="controller">
        </div>
        <div class="form-group">
            <label for="actions">Action name</label>
            <input type="text" class="form-control" id="actions" placeholder="single action name like index, add, list etc." name="action">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>

<div class="container">
<?php }
else if($success){ ?>
    <div class="alert alert-success" role="alert">
    <?php echo $message; ?> 
    </div>
    <a href="/acl/resource" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Go back</a>

<?php
} else {
?>
    <div class="alert alert-danger" role="alert">
    <?php echo $message; ?> 
    </div>
    <a href="/acl/resource" class="btn btn-primary btn-lg">Go back</a>
<?php 
} 
?>
</div>
<div class="jumbotron jumbotron-fluid">
    <div class="container">
    <h2>List resources</h2>
<?php
if ($resources != null && $resources->count() > 0 ) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#Id</th>
            <th>Resource</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="2">Resource count: <?php echo $resources->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($resources as $resource) { ?>
            <tr>
                <td><?php echo $resource->id; ?></td>
                <td><?php echo $resource->resource; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}
else
{
?>
<p>No resource found.</p> 
<?php } ?>
</div>
</div>

